# scripts/install.ps1
$ErrorActionPreference = "Stop"
$AppName = "mcp-proxy"
$GitHubRepo = "TheAICompanyLabs/mcp-proxy-open-source"

Write-Host "Installing Universal MCP Proxy for Windows..."

# Fetch latest release version
$ApiUrl = "https://api.github.com/repos/$GitHubRepo/releases/latest"
$Release = Invoke-RestMethod -Uri $ApiUrl
$Version = $Release.tag_name

if (-not $Version) {
    Write-Error "Failed to fetch latest version. Ensure the repository is public."
    exit 1
}

# Match the exact name generated by build.sh
$FileName = "$AppName-windows-amd64.exe.zip"
$DownloadUrl = "https://github.com/$GitHubRepo/releases/download/$Version/$FileName"

Write-Host "-> Downloading $Version..."
Invoke-WebRequest -Uri $DownloadUrl -OutFile $FileName

# Create destination directory
$InstallDir = "C:\mcp-proxy"
if (-not (Test-Path -Path $InstallDir)) {
    New-Item -ItemType Directory -Path $InstallDir | Out-Null
}

Write-Host "-> Extracting to $InstallDir..."
Expand-Archive -Path $FileName -DestinationPath $InstallDir -Force

# Rename the extracted binary to mcp-proxy.exe for easier terminal usage
$ExtractedFile = "$InstallDir\$AppName-windows-amd64.exe"
$FinalBinary = "$InstallDir\$AppName.exe"

if (Test-Path -Path $ExtractedFile) {
    Rename-Item -Path $ExtractedFile -NewName "$AppName.exe" -Force
}

Remove-Item -Path $FileName -Force

Write-Host "Installation complete!"
Write-Host "! Please add $InstallDir to your System Environment Variables (PATH) to use '$AppName' globally."
